// --- diet-fitness-frontend/components/PlanCard.tsx ---
import { Card, CardContent, Typography, Grid, Box } from '@mui/material';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline';

export default function PlanCard({ type, title, plan, icon }: { type: string; title: string; plan: string; icon: string }) {
  return (
    <Grid item xs={12} sm={6} md={6}> {/* Adjusted grid sizing */}
      <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column', transition: 'transform 0.2s ease-in-out', '&:hover': { transform: 'translateY(-5px)' } }}>
        <CardContent sx={{ flexGrow: 1 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <Typography variant="h4" sx={{ mr: 1 }}>{icon}</Typography> {/* Display the emoji icon */}
            <Typography variant="h6" component="h2" gutterBottom sx={{ fontWeight: 600, color: 'primary.dark' }}>
              {title}
            </Typography>
          </Box>
          <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6 }}>
            {plan}
          </Typography>
        </CardContent>
        <Box sx={{ p: 2, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', bgcolor: 'background.default', borderTop: '1px solid', borderColor: 'divider' }}>
          <CheckCircleOutlineIcon color="action" sx={{ mr: 1 }} />
          <Typography variant="caption" color="text.secondary">
            Generated by FitPlan AI
          </Typography>
        </Box>
      </Card>
    </Grid>
  );
}